### PR TITLE
generate reports for PMTCT risks

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
@jpaidoussi @rudigiesler @KaitCrawford @devchima ready for review

**Comment by DevChima** [comment]
+1

**Comment by rudigiesler** [comment]
I'm not too sure about having this in the identity store, since this is something specific to momconnect, not a general feature that all seed installations can use. 

Maybe we can achieve the same thing by making an http request for each risk level (ie. get all identities where `details->'pmtct'->'risk_status'=='high'`, `low` etc). In each response it gives the total count, so we can just pull that from the response.

We can then house the requests and report generation in ndoh-hub, and not have to touch the identity store.

**Comment by smn** [comment]
Agreed, that would be much better, is there a way we can query this via the API or are you suggesting we add that feature to the API?

**Comment by smn** [comment]
My worry about this is that the JSON blobs aren't indexed and so these queries are increasingly more expensive the more records we have. Generally these arbitrary queries do not scale well.

**Comment by rudigiesler** [comment]
@smn It might be expensive, but this isn't something that is run often is it?

We can do it through the API currently.

http://identity-store.momconnect.p16n.org/api/v1/identities/search?details__pmtct__risk_status=high

for an example.

**Comment by smn** [comment]
Replaced by https://github.com/praekeltfoundation/ndoh-hub/pull/79

**Pull request closed without merging**
