### PR TITLE
Allow Identity.failed_message_count to be Null

### PR DESCRIPTION
**Pull request by KaitCrawford**

### CODE REVIEW

**Comment by smn** [comment]
This seems very strange, any idea why this would be needed now? What change caused this?

**Comment by KaitCrawford** [comment]
@smn it seems this code was never actually deployed to production. Otherwise we would have been seeing this 2 months ago.

**Comment by smn** [comment]
:+1:

**Comment by KaitCrawford** [comment]
@smn any idea why this would be needed though? Wouldn't the `default` value be used if no value is specified?

**Comment by smn** [comment]
It should, is the db perhaps out of sync for some reason? Are there records in the db with a null value?

**Comment by KaitCrawford** [comment]
@smn yeah there would be but the migration should populate those

**Pull request merged**
