### PR TITLE
Switch to ModelSerializer for consistency

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by smn** [comment]
Was the URL based approach too much schlep? 
Why are we needing to `str()` the integers?

**Comment by imsickofmaps** [comment]
@smn we're not using it on the other services, I'd shifted from it since the initial usage of DRF. The URL-based approach seems generally to confuse other people working on a shared code base. (Note: we need docs, to reduce this). 

The `str()` is because it's a UUID object.

**Comment by imsickofmaps** [comment]
@gsvr ready for review

**Comment by gsvr** [comment]
:+1:

**Pull request merged**
